import { CourseStatuses, DefaultStage, Devices, GroupStatus, ItemQuestionType, ItemType, LeadInteractionType, LeadSource, MaterialItemType, MessageTemplateType, OrderStatus, QuestionChoiceType, SessionStatus, SupportTicketStatus, SystemFormTypes, UserNoteStatus, UserNoteTypes, UserRoles, UserScreen } from "@prisma/client";

export const validUserRoles = [UserRoles.Admin, UserRoles.ChatAgent, UserRoles.SalesAgent, UserRoles.Student, UserRoles.Teacher, UserRoles.Tester, UserRoles.OperationAgent] as const;
export const validUserScreens = [UserScreen.dashboard, UserScreen.operations_management, UserScreen.notes, UserScreen.groups, UserScreen.waiting_list, UserScreen.retintions, UserScreen.placement_tests, UserScreen.sessions, UserScreen.sales_management, UserScreen.orders, UserScreen.leads, UserScreen.users_management, UserScreen.students, UserScreen.ops_team, UserScreen.edu_team, UserScreen.chat_agents, UserScreen.account, UserScreen.system_management, UserScreen.config, UserScreen.content, UserScreen.privacy, UserScreen.terms, UserScreen.documentation, UserScreen.support, UserScreen.tickets] as const;
export const validDeviceTypes = [Devices.Desktop, Devices.Mobile, Devices.Tablet] as const;
export const validGroupStatuses = [GroupStatus.Active, GroupStatus.Cancelled, GroupStatus.Inactive, GroupStatus.Paused, GroupStatus.Waiting, GroupStatus.Completed] as const;
export const validSessionStatuses = [SessionStatus.Scheduled, SessionStatus.Starting, SessionStatus.Ongoing, SessionStatus.Completed, SessionStatus.Cancelled] as const;
export const validCourseStatuses = [CourseStatuses.Waiting, CourseStatuses.Completed, CourseStatuses.Ongoing, CourseStatuses.Postponded, CourseStatuses.Refunded, CourseStatuses.Cancelled, CourseStatuses.OrderCreated, CourseStatuses.OrderPaid] as const;
export const validSystemFormTypes = [SystemFormTypes.Assignment, SystemFormTypes.Quiz, SystemFormTypes.PlacementTest, SystemFormTypes.FinalTest] as const;
export const validOrderStatuses = [OrderStatus.Cancelled, OrderStatus.Paid, OrderStatus.Pending, OrderStatus.Refunded] as const;
export const validNoteTypes = [UserNoteTypes.ComplainLevel1, UserNoteTypes.ComplainLevel2, UserNoteTypes.ComplainLevel3, UserNoteTypes.Feedback, UserNoteTypes.Followup, UserNoteTypes.Info, UserNoteTypes.Query] as const;
export const validMaterialItemTypes = [MaterialItemType.Manual, MaterialItemType.Upload] as const;
export const validNoteStatus = [UserNoteStatus.Closed, UserNoteStatus.Created, UserNoteStatus.Opened] as const;
export const validTrueOrFalse = ["true", "false"] as const;
export const validLeadSources = [LeadSource.Facebook, LeadSource.Instagram, LeadSource.Manual, LeadSource.Other, LeadSource.WhatsApp] as const;
export const validSupportTicketStatus = [SupportTicketStatus.Closed, SupportTicketStatus.Created, SupportTicketStatus.Opened] as const;
export const validDefaultStages = [DefaultStage.Intake, DefaultStage.Qualified, DefaultStage.Converted, DefaultStage.NotQualified, DefaultStage.Lost] as const;
export const validLeadInteractionsType = [LeadInteractionType.Call, LeadInteractionType.Chat, LeadInteractionType.Meeting] as const;
export const validMessageTemplateTypes = [MessageTemplateType.AddedToGroup, MessageTemplateType.AddedToWaitingList, MessageTemplateType.ConfirmEmail, MessageTemplateType.Custom, MessageTemplateType.EmailConfirmed, MessageTemplateType.GroupCompleted, MessageTemplateType.OrderCancelled, MessageTemplateType.OrderPaid, MessageTemplateType.OrderPlaced, MessageTemplateType.OrderRefunded, MessageTemplateType.PlacementTestRescheduled, MessageTemplateType.PlacementTestScheduled, MessageTemplateType.SessionCompleted, MessageTemplateType.SessionStarted, MessageTemplateType.SessionStartingSoon, MessageTemplateType.Welcome, MessageTemplateType.CredentialsEmail, MessageTemplateType.CertificateReady] as const;
export const validItemTypes = [ItemType.ImageItem, ItemType.PageBreakItem, ItemType.QuestionItem, ItemType.TextItem, ItemType.VideoItem, ItemType.QuestionGroupItem] as const;
export const validItemQuestionTypes = [ItemQuestionType.Choice, ItemQuestionType.Text] as const;
export const validQuestionChoiceTypes = [QuestionChoiceType.Checkbox, QuestionChoiceType.Radio] as const;
